# SPDX-FileCopyrightText: 2023 Matthew Nickson <mnickson@sidingsmedia.com>
# SPDX-License-Identifier: CC0-1.0

name: Docker Image CI

on: 
  release:
    types: 
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Docker
      run: echo ${{secrets.DOCKER_PASSWORD}} | docker login -u ${{secrets.DOCKER_USER}} --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag asset-tags:latest

    - name: Tag image
      run: docker tag asset-tags:latest asset-tags:${{github.ref_name}}
      
    - name: Publish image
      run: docker push asset-tags:${{github.ref_name}}
